services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${APP_PORT}
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${DB_HOSTNAME_PROD}:${DB_PORT}/{MONGO_DB}?authSource=admin
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - wharena-network

  trait-service:
    container_name: trait-service
    build:
      context: ./trait-service
    ports:
      - ${TRAIT_SERVICE_PORT}:${TRAIT_SERVICE_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${TRAIT_SERVICE_PORT}
      - MONGO_URI=mongodb://{DB_HOSTNAME_PROD}:${DB_PORT}/{MONGO_DB}
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TRAIT_SERVICE_PORT}/traits/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trait-network
      - wharena-network

  armor-service:
    container_name: armor-service
    build:
      context: ./armor-service
    ports:
      - ${ARMOR_SERVICE_PORT}:${ARMOR_SERVICE_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${ARMOR_SERVICE_PORT}
      - MONGO_URI=mongodb://{DB_HOSTNAME_PROD}:${DB_PORT}/{MONGO_DB}
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${ARMOR_SERVICE_PORT}/armors/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - armor-network
      - wharena-network

  weapon-service:
    container_name: weapon-service
    build:
      context: ./weapon-service
    ports:
      - ${WEAPON_SERVICE_PORT}:${WEAPON_SERVICE_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${WEAPON_SERVICE_PORT}
      - MONGO_URI=mongodb://{DB_HOSTNAME_PROD}:${DB_PORT}/{MONGO_DB}
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEAPON_SERVICE_PORT}/weapons/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - weapon-network
      - wharena-network

  talent-service:
    container_name: talent-service
    build:
      context: ./talent-service
    ports:
      - ${TALENT_SERVICE_PORT}:${TALENT_SERVICE_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${TALENT_SERVICE_PORT}
      - MONGO_URI=mongodb://{DB_HOSTNAME_PROD}:${DB_PORT}/{MONGO_DB}
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TALENT_SERVICE_PORT}/talents/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - talent-network
      - wharena-network

  skill-service:
    container_name: skill-service
    build:
      context: ./skill-service
    ports:
      - ${SKILL_SERVICE_PORT}:${SKILL_SERVICE_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${SKILL_SERVICE_PORT}
      - MONGO_URI=mongodb://{DB_HOSTNAME_PROD}:${DB_PORT}/{MONGO_DB}
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SKILL_SERVICE_PORT}/skills/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skill-network
      - wharena-network

  character-service:
    container_name: character-service
    build:
      context: ./character-service
    ports:
      - ${CHARACTER_SERVICE_PORT}:${CHARACTER_SERVICE_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${CHARACTER_SERVICE_PORT}
      - MONGO_URI=mongodb://{DB_HOSTNAME_PROD}:${DB_PORT}/{MONGO_DB}
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CHARACTER_SERVICE_PORT}/characters/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - character-network
      - wharena-network

networks:
  wharena-network:
    driver: bridge
  trait-network:
    driver: bridge
  armor-network:
    driver: bridge
  weapon-network:
    driver: bridge
  talent-network:
    driver: bridge
  skill-network:
    driver: bridge
  character-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local